### PR TITLE
Update bundle_zh_CN.properties

### PR DESCRIPTION
**Pull request by Linnnnnnnnnna**
@StormyBytes what Seer mean

and what is its function

### CODE REVIEW

**Comment by sbxte** [comment]
Seer is meant to be a client side player behaviour scoring system (antigrief basically). Right now it's broken but still used for !seer which lists out players and their IDs. Someone on discord requested I put it out of client experimentals because of how useful it is.

**Comment by Linnnnnnnnnna** [comment]
> Seer is meant to be a client side player behaviour scoring system (antigrief basically). Right now it's broken but still used for !seer which lists out players and their IDs. Someone on discord requested I put it out of client experimentals because of how useful it is.

ad

**Comment by Linnnnnnnnnna** [comment]
> Seer is meant to be a client side player behaviour scoring system (antigrief basically). Right now it's broken but still used for !seer which lists out players and their IDs. Someone on discord requested I put it out of client experimentals because of how useful it is.

how to use

**Comment by Linnnnnnnnnna** [comment]
se


and i didn't saw setting.seer-warnings.name/setting.seer-scoring.name

**Comment by Linnnnnnnnnna** [comment]
@StormyBytes , time to merge this

**Pull request merged**
