### PR TITLE
Update bundle_zh_CN.properties

### PR DESCRIPTION
**Pull request by Linnnnnna**
@StormyBytes all done（）

98A)ZCD4$4ML~G_@JIRCS@D

### CODE REVIEW

**Comment by buthed010203** [comment]
Why is this meme just a screenshot of a chibi kiriko with a megaphone taken on an ios device that's on a really old version of ios

**Comment by Linnnnnna** [comment]
> Why is this meme just a screenshot of a chibi kiriko with a megaphone taken on an ios device that's on a really old version of ios

https://www.bilibili.com/video/BV1H8411W7qw/
https://t.bilibili.com/715627206234079249?spm_id_from=333.999.0.0

too loud (and size is normal on chat software )

Z35SWISN9CXE 1B6ZOJYGQU

**Comment by Linnnnnna** [comment]
@buthed010203 
how can I know you read my reply ( )

**Comment by buthed010203** [comment]
h

**Comment by Linnnnnna** [comment]
~{_BY 0KQ4GT5WGWF%OO%Q4

**Pull request merged**
