### PR TITLE
V.8 jp lang update

### PR DESCRIPTION
**Pull request by wancor1**

### CODE REVIEW

**Comment by buthed010203** [comment]
I would prefer if you would put the non `client.__` translations in vanilla as they cause merge conflicts otherwise which are a pain to deal with

**Comment by wancor1** [comment]
sry

**Comment by wancor1** [comment]
Could you explain how I can edit the files again?

**Comment by wancor1** [comment]
Oh, I don't know why, but I managed to do it.

**Comment by buthed010203** [comment]
Thank you for only changing client strings

**Pull request merged**
