### PR TITLE
I re-translated a part of it.

### PR DESCRIPTION
**Pull request by wancor1**

### CODE REVIEW

**Comment by JasonP01** [comment]
You know you can press edit file on github itself to update translations, you dont need to upload file separately

**Comment by wancor1** [comment]
This time is an exception, but whenever a new translation is added, we use a program that shows where the changes are because it's difficult to see what's different, so we always upload it.
So it can't be helped. I don't know any other way.

**Comment by wancor1** [comment]
I just found out for the first time that I have the permission to change the contents of the file here.

**Comment by wancor1** [comment]
I was wrong.

**Pull request closed without merging**
