### PR TITLE
Add Custom Client identity on server.

### PR DESCRIPTION
**Pull request by way-zer**
When connect to server.
```
Call.serverPacketReliable("FOO.VERSION",Version.clientVersion);
```

Let server plugin to recoginize whether it is custom client. And get the version used.

### CODE REVIEW

**Comment by buthed010203** [comment]
But why though

**Comment by way-zer** [comment]
Provide a way for server to distinguish foo with offical.

**Comment by buthed010203** [comment]
But why...

**Comment by way-zer** [comment]
some feature in foo may be cheat

Server can show warning targeted to foo users

**Comment by buthed010203** [comment]
Then tell people not to use it? This will just get circumvented by forks making it even more unfair as those are harder to come by... As it is the client already displays a warning when connecting to pvp servers

**Comment by way-zer** [comment]
Some users get banned but don't know why. Just use some feature may be cheat in pvp.

Pvp is an example. Some features are forbidden in other mode.

**Comment by buthed010203** [comment]
Use the `fooCheck` packet thats sent to the server for that instead.

**Comment by way-zer** [comment]
What is `fooCheck`

**Comment by buthed010203** [comment]
Pretty much what you proposed here, the client sends a packet called `fooCheck` on join rather than `FOO.VERSION`.

**Comment by way-zer** [comment]
Could you give me a link to the source. I can't find it.

**Comment by buthed010203** [comment]
It's literally just an empty packet, just check if the user sends one to the server as you would have with this pr but change the name from `FOO.VERSION` to `fooCheck`

**Comment by way-zer** [comment]
Emm...., I find it in `v7`. It can't be `petty much`, just a empty packet.

And this seems useless.
Snipaste_2022-04-27_23-52-29
Snipaste_2022-04-27_23-52-48

I know the other one can work.

**Comment by buthed010203** [comment]
I fixed that locally a couple of weeks ago, not that its important though since thats only used if you're hosting a game

**Comment by suspicious-pineapple** [comment]
> Some users get banned but don't know why

telling the server that you are using a modified client will surely help with this, i can't see how it could possibly go wrong

**Pull request closed without merging**
