### PR TITLE
Added dps graph in editor, unit payload update in the CustomRulesDialog, and more brush sizes for editor

### PR DESCRIPTION
**Pull request by TheEt1234**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by TheEt1234** [comment]
._.

**Comment by TheEt1234** [comment]
Am i inpatient or does 6 days look like a lot

**Comment by TheEt1234** [comment]
2 weeks . _ .

**Comment by BalaM314** [comment]
Thank you for your contribution!

**Pull request merged**
