### PR TITLE
see items in junctions

### PR DESCRIPTION
**Pull request by zxtej**
why? why not
adds a setting under client > graphics & appearance
and also adds functionality to add an Intc to a slider because it somehow just wasnt a thing previously

### CODE REVIEW

**Comment by zxtej** [comment]
as for the fail build, could make it check settings every time it draws or hide the initialization Core.settings check somewhere in init if it actually causes problems on some devices h

**Comment by buthed010203** [comment]
Dont add a new slider pref, just use the string processor to set the var `s -> { whatever = s; return s; }`. Also tests fail, make sure to check that Core.settings != null

**Comment by zxtej** [comment]
aite, implemented the changes

**Comment by buthed010203** [comment]
Why can you self request reviews lmfao

**Pull request merged**
